import random as rng

from redbot.core import commands

class Quotes(commands.Cog):
    """This is sending you a random quote from the list.

    Please do not take all of this seriously, this is a quote cog and not meant to be seriously."""

    async def red_delete_data_for_user(self, **kwargs):
        """Nothing to delete."""
        return

    def __init__(self, bot):
        self.bot = bot

		# i wanted to use api for this but i did not find any on google...
		# if you have an api and know how it works, you're free to PR this, please do so before i keep adding more quotes.
		# And if you're going to steal this, please make sure you give credits. this took me 3 days to finish amount of words and dont claim it as yours. :)

    @commands.cooldown(1, 5, commands.BucketType.guild)
    @commands.max_concurrency(1, commands.BucketType.guild)
    @commands.command(aliases=["quote"])
    async def quotes(self, ctx):
        """Displays random quotes."""
        words = rng.choice([
        	"Better to remain silent and be thought a fool than to speak out and remove all doubt.",
        	"If I were two-faced, would I be wearing this one?",
        	"The best thing about the future is that it comes one day at a time.",
        	"The only mystery in life is why the kamikaze pilots wore helmets.",
        	"Light travels faster than sound. This is why some people appear bright until you hear them speak.",
        	"Nobody realizes that some people expend tremendous energy merely to be normal.",
        	"Men marry women with the hope they will never change. Women marry men with the hope they will change. Invariably they are both disappointed.",
        	"The difference between stupidity and genius is that genius has its limits.",
        	"All the things I really like to do are either immoral, illegal or fattening.",
        	"War is God’s way of teaching Americans geography",
        	"It would be nice to spend billions on schools and roads, but right now that money is desperately needed for political ads.",
        	"The average dog is a nicer person than the average person.",
        	"At every party there are two kinds of people – those who want to go home and those who don’t. The trouble is, they are usually married to each other.",
        	"If you want your children to listen, try talking softly to someone else",
        	"I don’t believe in astrology; I’m a Sagittarius and we’re skeptical.",
        	"My opinions may have changed, but not the fact that I’m right.",
        	"To be sure of hitting the target, shoot first, and call whatever you hit the target.",
        	"Trouble knocked at the door, but, hearing laughter, hurried away.",
        	"Wine is constant proof that God loves us and loves to see us happy.",
        	"Have you noticed that all the people in favor of birth control are already born?",
        	"Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind.",
        	"Most people would sooner die than think; in fact, they do so.",
        	"The world is full of magical things patiently waiting for our wits to grow sharper.",
        	"Facebook just sounds like a drag, in my day seeing pictures of peoples vacations was considered a punishment.",
        	"Everything that used to be a sin is now a disease.",
        	"If there is anything the nonconformist hates worse than a conformist, it’s another nonconformist who doesn’t conform to the prevailing standard of nonconformity.",
        	"Money won’t buy happiness, but it will pay the salaries of a large research staff to study the problem.",
        	"The surest sign that intelligent life exists elsewhere in the universe is that it has never tried to contact us.",
        	"Before you judge a man, walk a mile in his shoes. After that who cares?… He’s a mile away and you’ve got his shoes!",
        	"I’ve always wanted to go to Switzerland to see what the army does with those wee red knives.",
        	"Going to church doesn’t make you a Christian any more than going to a garage makes you an automobile.",
        	"A bank is a place that will lend you money if you can prove that you don’t need it",
        	"Inside me there’s a thin person struggling to get out, but I can usually sedate him with four or five cupcakes.",
        	"We never really grow up, we only learn how to act in public",
        	"As a child my family’s menu consisted of two choices: take it or leave it",
        	"My favorite machine at the gym is the vending machine.",
        	"All right everyone, line up alphabetically according to your height.",
        	"He who laughs last didn’t get the joke",
        	"I always arrive late at the office, but I make up for it by leaving early.",
        	"Don’t worry about the world coming to an end today. It is already tomorrow in Australia.",
        	"By the time a man realizes that his father was right, he has a son who thinks he’s wrong.",
        	"A day without laughter is a day wasted.",
        	"Political correctness is tyranny with manners.",
        	"High heels were invented by a woman who had been kissed on the forehead",
        	"If you love something set it free, but don’t be surprised if it comes back with herpes.",
        	"When I was a boy I was told that anybody could become President. I’m beginning to believe it.",
        	"A stockbroker urged me to buy a stock that would triple its value every year. I told him, ‘At my age, I don’t even buy green bananas.",
        	"They say marriages are made in Heaven. But so is thunder and lightning.",
        	"I’m too drunk to taste this chicken.",
        	"A study in the Washington Post says that women have better verbal skills than men. I just want to say to the authors of that study: ‘Duh.'",
        	"Starbucks says they are going to start putting religious quotes on cups. The very first one will say, ‘Jesus! This cup is expensive!'",
        	"Laughing at our mistakes can lengthen our own life. Laughing at someone else’s can shorten it.",
        	"If you can’t live without me, why aren’t you trying already to get me?",
        	"If you think you are too small to make a difference, try sleeping with a mosquito.",
        	"Remember, today is the tomorrow you worried about yesterday",
        	"Education is learning what you didn’t even know you didn’t know",
        	"It is a scientific fact that your body will not absorb cholesterol if you take it from another person’s plate.",
        	"Never under any circumstances take a sleeping pill and a laxative on the same night.",
        	"I used to jog but the ice cubes kept falling out of my glass.",
        	"Everyone has a purpose in life. Perhaps yours is watching television.",
        	"The digital camera is a great invention because it allows us to reminisce. Instantly",
        	"A failure is like fertilizer; it stinks to be sure, but it makes things grow faster in the future.",
        	"Biologically speaking, if something bites you it’s more likely to be female.",
        	"As long as people will accept crap, it will be financially profitable to dispense it.",
        	"A pessimist is a person who has had to listen to too many optimists.",
        	"The cure for boredom is curiosity. There is no cure for curiosity.",
        	"Never doubt the courage of the French. They were the ones who discovered that snails are edible.",
        	"Human beings, who are almost unique in having the ability to learn from the experience of others, are also remarkable for their apparent disinclination to do so.",
        	"I refuse to answer that question on the grounds that I don’t know the answer.",
        	"Don’t cry because it’s over. Smile because it happened.",
        	"I was born to make mistakes, not to fake perfection.",
        	"Analyzing humor is like dissecting a frog. Few people are interested and the frog dies of it.",
        	"If you think nobody cares if you’re alive, try missing a couple of car payments.",
        	"The duty of a patriot is to protect his country from its government.",
        	"Do not take life too seriously. You will never get out of it alive.",
        	"A woman is like a tea bag – you can’t tell how strong she is until you put her in hot water.",
        	"A computer once beat me at chess, but it was no match for me at kick boxing",
        	"How many people here have telekenetic powers? Raise my hand",
        	"I asked God for a bike, but I know God doesn’t work that way. So I stole a bike and asked for forgiveness.",
        	"Leave something for someone but dont leave someone for something.",
        	"Never go to a doctor whose office plants have died.",
        	"I drink to make other people more interesting.",
        	"Great art is the contempt of a great man for small art.",
        	"You’re only as good as your last haircut.",
        	"Good advice is something a man gives when he is too old to set a bad example.",
        	"Marriage is the only war in which you sleep with the enemy.",
        	"I can’t understand why a person will take a year to write a novel when he can easily buy one for a few dollars.",
        	"The first time I sang in the church choir; two hundred people changed their religion.",
			"Patriotism is your conviction that this country is superior to all others because you were born in it.",
			"We learn from experience that men never learn anything from experience.",
			"Happiness is having a large, loving, caring, close-knit family in another city",
			"If you live to be one hundred, you’ve got it made. Very few people die past that age.",
			"You know you’re getting old when you stoop to tie your shoelaces and wonder what else you could do while you’re down there.",
			"Have you ever noticed that anybody driving slower than you is an idiot, and anyone going faster than you is a maniac?",
			"I was thinking about how people seem to read the Bible a whole lot more as they get older; then it dawned on me – they’re cramming for their final exam.",
			"I’m in shape. Round is a shape.",
			"If you try to fail, and succeed, which have you done?",
			"May the forces of evil become confused on the way to your house.",
			"Most people work just hard enough not to get fired and get paid just enough money not to quit.",
			"One tequila, two tequila, three tequila, floor.",
			"Whoever said money can’t buy happiness didn’t know where to shop.",
			"A black cat crossing your path signifies that the animal is going somewhere.",
			"Behind every successful man is a woman, behind her is his wife.",
			"Here’s to our wives and girlfriends…may they never meet!",
			"I refuse to join any club that would have me as a member.",
			"I was married by a judge. I should have asked for a jury.",
			"If you find it hard to laugh at yourself, I would be happy to do it for you.",
			"Marriage is the chief cause of divorce.",
			"A judge is a law student who marks his own examination papers.",
			"The two most common elements in the universe are hydrogen and stupidity.",
			"It’s only when you look at an ant through a magnifying glass on a sunny day that you realize how often they burst into flames.",
			"It’s a recession when your neighbor loses his job; it’s a depression when you lose yours.",
			"Before marriage, a man declares that he would lay down his life to serve you; after marriage, he won’t even lay down his newspaper to talk to you.",
			"Life begins at 40 – but so do fallen arches, rheumatism, faulty eyesight, and the tendency to tell a story to the same person, three or four times.",
			"I’ve got all the money I’ll ever need, if I die by four o’clock.",
			"If you’re going to do something tonight that you’ll be sorry for tomorrow morning, sleep late.",
			"All men are equal before fish.",
			"If I want to knock a story off the front page, I just change my hairstyle",
			"You tried your best and you failed miserably. The lesson is never try.",
			"People who think they know everything are a great annoyance to those of us who do.",
			"I’d rather have 1% of the effort of 100 men than 100% of my own effort",
			"Money is not the most important thing in the world. Love is. Fortunately, I love money.",
			"Women are wiser than men because they know less and understand more.",
			"When we talk to God, we’re praying. When God talks to us, we’re schizophrenic.",
			"According to a new survey, 90% of men say their lover is also their best friend. Which is really kind of disturbing when you consider man’s best friend is his dog.",
			"Here’s something to think about: How come you never see a headline like ‘Psychic Wins Lottery’?",
			"My pessimism extends to the point of even suspecting the sincerity of other pessimists.",
			"Haters are just confused admirers because they can’t figure out the reason why everyone loves you.",
			"It’s amazing that the amount of news that happens in the world every day always just exactly fits the newspaper.",
			"Laugh a lot. It burns a lot of calories.",
			"Avoid fruits and nuts. You are what you eat",
			"The simple act of opening a bottle of wine has brought more happiness to the human race than all the collective governments in the history of earth.",
			"Age is just a number. It’s totally irrelevant unless, of course, you happen to be a bottle of wine",
			"Why is there so much month left at the end of the money?",
			"Forgive your enemies, but never forget their names.",
			"I’ve come to view Jesus much the way I view Elvis. I love the guy but the fan clubs really freak me out.",
			"Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it.",
			"The avoidance of taxes is the only intellectual pursuit that still carries any reward.",
			"Life is hard; it’s harder if you’re stupid",
			"If life was fair, Elvis would be alive and all the impersonators would be dead.",
			"Flattery is like cologne water, to be smelt, not swallowed.",
			"The greatest thief this world has ever produced is procrastination, and he is still at large.",
			"The secret of the demagogue is to make himself as stupid as his audience so they believe they are clever as he.",
			"Life is hard. After all, it kills you.",
			"The safe way to double your money is to fold it over once and put it in your pocket.",
			"True terror is to wake up one morning and discover that your high school class is running the country",
			"A successful man is one who makes more money than his wife can spend. A successful woman is one who can find such a man.",
			"A man doesn’t know what he knows until he knows what he doesn’t know.",
			"Originality is the fine art of remembering what you hear but forgetting where you heard it.",
			"If you’re too open-minded; your brains will fall out.",
			"I always wanted to be somebody, but now I realize I should have been more specific.",
			"The road to success is always under construction.",
			"Until you value yourself, you won’t value your time. Until you value your time, you will not do anything with it.",
			"Don’t keep a man guessing too long – he’s sure to find the answer somewhere else.",
			"I’m not for everyone. I’m barely for me.",
			"Cleaning up with children around is like shoveling during a blizzard.",
			"Always remember that you are absolutely unique. Just like everyone else.",
			"Age is an issue of mind over matter. If you don’t mind, it doesn’t matter.",
			"Be careful about reading health books. You may die of a misprint.",
			"Clothes make the man. Naked people have little or no influence on society",
			"I am an old man and have known a great many troubles, but most of them never happened.",
			"I am only human, although I regret it.",
			"I would have written a shorter letter, but I did not have the time.",
			"Never put off till tomorrow what you can do the day after tomorrow.",
			"The only way to keep your health is to eat what you don’t want, drink what you don’t like, and do what you’d rather not.",
			"When we remember we are all mad, the mysteries disappear and life stands explained.",
			"Worrying is like paying a debt you don’t owe.",
			"Do not make the mistake of treating your dogs like humans or they will treat you like dogs.",
			"Son, if you really want something in this life, you have to work for it. Now quiet! They’re about to announce the lottery numbers.",
			"God is at home, it’s we who have gone out for a walk.",
			"In the past 10,000 years, humans have devised roughly 100,000 religions based on roughly 2,500 gods. So the only difference between myself and the believers is that I am skeptical of 2,500 gods whereas they are skeptical of 2,499 gods. We’re only one God away from total agreement.",
			"My theory is that all of Scottish cuisine is based on a dare.",
			"Knowledge is knowing a tomato is a fruit; wisdom is not putting it in a fruit salad.",
			"A committee is a group that keeps minutes and loses hours.",
			"If evolution really works, how come mothers only have two hands?",
			"My doctor told me that jogging could add years to my life. I think he was right. I feel ten years older already",
			"I drank some boiling water because I wanted to whistle.",
			"I prefer someone who burns the flag and then wraps themselves up in the Constitution over someone who burns the Constitution and then wraps themselves up in the flag.",
			"It’s just a job. Grass grows, birds fly, waves pound the sand. I beat people up.",
			"God did not intend religion to be an exercise club.",
			"The only time a woman really succeeds in changing a man is when he is a baby.",
			"It’s always darkest before the dawn. So if you’re going to steal your neighbor’s newspaper, that’s the time to do it.",
			"The only thing that stops God from sending another flood is that the first one was useless.",
			"When you go into court you are putting your fate into the hands of twelve people who weren’t smart enough to get out of jury duty.",
			"As you get older three things happen. The first is your memory goes, and I can’t remember the other two.",
			"Ask me no questions, and I’ll tell you no lies.",
			"If you must make a noise, make it quietly.",
			"A woman’s mind is cleaner than a man’s: She changes it more often.",
			"Man has his will, but woman has her way.",
			"Roses are red, violets are blue, I’m schizophrenic, and so am I.",
			"There’s a fine line between genius and insanity. I have erased this line.",
			"What the world needs is more geniuses with humility; there are so few of us left.",
			"Always borrow money from a pessimist. He won’t expect it back.",
			"Always forgive your enemies – nothing annoys them so much.",
			"I am so clever that sometimes I don’t understand a single word of what I am saying.",
			"I can resist everything except temptation.",
			"I can stand brute force, but brute reason is quite unbearable. There is something unfair about its use. It is hitting below the intellect",
			"Women are meant to be loved, not to be understood.",
			"Of all the things I’ve lost I miss my mind the most.",
			"The only reason some people get lost in thought is because it’s unfamiliar territory.",
			"To err is human, but to really foul things up you need a computer",
			"I have learned from my mistakes, and I am sure I can repeat them exactly.",
			"I want my children to have all the things I couldn’t afford. Then I want to move in with them.",
			"We spend the first twelve months of our children’s lives teaching them to walk and talk and the next twelve telling them to sit down and shut up.",
			"When a man opens a car door for his wife, it’s either a new car or a new wife.",
			"Life is a sexually transmitted disease",
			"I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives.",
			"Health nuts are going to feel stupid someday, lying in hospitals dying of nothing.",
			"The less Holy Spirit we have, the more cake and coffee we need to keep the church going.",
			"If you lived with a roommate as unstable as this economic system, you would’ve moved out or demanded that your roommate get professional help.",
			"When you’re in love it’s the most glorious two and a half days of your life.",
			"Lead me not into temptation; I can find the way myself.",
			"I love being married. It’s so great to find that one special person you want to annoy for the rest of your life.",
			"When I eventually met Mr. Right I had no idea that his first name was Always.",
			"If you have a secret, people will sit a little bit closer.",
			"I have tried to know absolutely nothing about a great many things, and I have succeeded fairly well.",
			"The man who smiles when things go wrong has thought of someone to blame it on.",
			"All my life I’ve wanted, just once, to say something clever without losing my train of thought.",
			"By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day.",
			"Love is an irresistible desire to be irresistibly desired.",
			"We’re all a little weird. And life is a little weird. And when we find someone whose weirdness is compatible with ours, we join up with them and fall into mutually satisfying weirdness — and call it love — true love",
			"Older people shouldn’t eat health food, they need all the preservatives they can get.",
			"I’m sorry, if you were right, I’d agree with you.",
			"Why do they call it rush hour when nothing moves?",
			"I found there was only one way to look thin: hang out with fat people.",
			"I looked up my family tree and found out I was the sap.",
			"My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you’re ugly too.",
			"We sleep in separate rooms, we have dinner apart, we take separate vacations – we’re doing everything we can to keep our marriage together.",
			"I believe that if life gives you lemons, you should make lemonade… And try to find somebody whose life has given them vodka, and have a party.",
			"It’s true hard work never killed anybody, but I figure, why take the chance?",
			"Recession is when a neighbor loses his job. Depression is when you lose yours.",
			"Have no fear of perfection. You’ll never reach it.",
			"Inflation is when you pay fifteen dollars for the ten-dollar haircut you used to get for five dollars when you had hair.",
			"A verbal contract isn’t worth the paper it’s written on.",
			"I don’t think anyone should write their autobiography until after they’re dead.",
			"I don’t want any yes-men around me. I want everybody to tell me the truth even if it costs them their job.",
			"I wish I were dumber so I could be more certain about my opinions. It looks fun.",
			"If there are no stupid questions, then what kind of questions do stupid people ask? Do they get smart just in time to ask questions?",
			"I live by my own rules (reviewed, revised, and approved by my wife).. but still my own.",
			"The trouble with telling a good story is that it invariably reminds the other fellow of a dull one.",
			"Children today are tyrants. They contradict their parents, gobble their food, and tyrannize their teachers.",
			"You cannot be anything if you want to be everything.",
			"If any of you cry at my funeral I’ll never speak to you again.",
			"Folks, I don’t trust children. They’re here to replace us.",
			"Crocodiles are easy. They try to kill and eat you. People are harder. Sometimes they pretend to be your friend first.",
			"A day without sunshine is like, you know, night.",
			"It does not matter whether you win or lose, what matters is whether I win or lose!",
			"A clear conscience is usually the sign of a bad memory.",
			"I intend to live forever. So far, so good.",
			"The early bird gets the worm, but the second mouse gets the cheese.",
			"To steal ideas from one person is plagiarism; to steal from many is research.",
			"You can’t have everything. Where would you put it?",
			"When I hear somebody sigh, ‘Life is hard,’ I am always tempted to ask, ‘Compared to what?'",
			"The world is a globe. The farther you sail, the closer to home you are.",
			"If you could kick the person in the pants responsible for most of your trouble, you wouldn’t sit for a month.",
			"I have not failed. I’ve just found 10,000 ways that won’t work.",
			"Opportunity is missed by most people because it is dressed in overalls and looks like work.",
			"It takes considerable knowledge just to realize the extent of your own ignorance.",
            "Happiness is an imaginary condition, formerly attributed by the living to the dead, now usually attributed by adults to children, and by children to adults.",
            "I know that there are people who do not love their fellow man, and I hate people like that!",
            "Every man is guilty of all the good he did not do.",
            "A rich man is nothing but a poor man with money.",
            "Always carry a flagon of whiskey in case of snakebite and furthermore always carry a small snake.",
            "If at first you don’t succeed, try, try again. Then quit. There’s no point in being a damn fool about it.",
            "We are all here on earth to help others. What on earth the others are here for I don’t know",
            "A great pleasure in life is doing what people say you cannot do.",
            "My doctor gave me six months to live, but when I couldn’t pay the bill he gave me six months more.",
            "Give me a woman who loves beer and I will conquer the world.",
            "Half our life is spent trying to find something to do with the time we have rushed through life trying to save.",
            "The road to success is dotted with many tempting parking spaces.",
            "Common sense and a sense of humor are the same thing, moving at different speeds. A sense of humor is just common sense, dancing.",
            "A lie gets halfway around the world before the truth has a chance to get its pants on.",
            "If you’re going through hell, keep going",
            "You have enemies? Good. That means you’ve stood up for something, sometime in your life.",
            "I don’t want to achieve immortality through my work. I want to achieve it through not dying.",
            "I’m such a good lover because I practice a lot on my own.",
            "Marriage is like mushrooms: we notice too late if they are good or bad.",
            "Everybody laughs the same in every language because laughter is a universal connection.",
            "Always go to other people’s funerals, otherwise they won’t come to yours.",
            "If you come to a fork in the road, take it.",
            "You’ve got to be very careful if you don’t know where you are going, because you might not get there.",
            "People often say that motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily.",
            "A man in love is incomplete until he has married. Then he’s finished.",
            "When on the ladder of success, don’t let boys look up your dress!",
            "Time is a great teacher, but unfortunately it kills all its pupils",
            "There is a place you can touch a woman that will drive her crazy. Her heart."
            "Always remember that true beauty comes from within – from within bottles, jars, compacts, and tubes.",
            "Every day I get up and look through the Forbes list of the richest people in America. If I’m not there, I go to work.",
            "Son, if you really want something in this life, you have to work for it. Now quiet! They’re about to announce the lottery numbers.",
            "I always wanted to be somebody, but now I realize I should have been more specific.",
            "I am not a vegetarian because I love animals; I am a vegetarian because I hate plants.",
            "Women: Can’t live with them, can’t bury them in the backyard without the neighbors seeing.",
            "What are the three words guaranteed to humiliate men everywhere? ‘Hold my purse.",
            "Tell a man there are 300 billion stars in the universe and he’ll believe you. Tell him a bench has wet paint on it and he’ll have to touch it to be sure.",
            "If you can’t see the bright side of life, polish the dull side.",
            "On the keyboard of life, always keep one finger on the Escape key.",
            "In life, it’s not who you know that’s important, it’s how your wife found out.",
            "Life loves to be taken by the lapel and told, I am with you kid. Let’s go!",
            "A celebrity is a person who works hard all his life to become well-known, then wears dark glasses to avoid being recognized.",
            "Don’t worry about the world coming to an end today. It is already tomorrow in Australia.",
            "Love your enemies. It makes them so damned mad.",
            "Unfortunately, son, we Simpsons sometimes have to bend the rules a little in order to hold our own.",
        ])
        await ctx.send(words)
