BEG_WORDS = [
    "Nice you got:",
    "Someone felt nice and gave you:",
    "What a lucky day, you got:",
    "A woman passed by you and felt bad. So she gave you:",
    "You looked like someone who needed more coins so you got:",
    "The wait is over, you got:",
    "Nice today you're lucky and got:",
    "You robbed a bank and found:",
    "You stole some coins from your mom and found:",
    "Some friends gave you:",
    "Your dad randomly gave you:",
    "Someone was friendly so you got:",
    "Your best friend wanted to give you birthday coins:",
    "While walking to store, you found:",
    "You beg for coins to your dad and got:",
    "You beg for coins to your mom and got:",
    "A man felt so sad for you so he gave you:",
    "Today is your day and you got so lucky and got:",
    "Streamer Admiralbharoo gave you:",
    "You went though old clothes and found:",
    "You wanted to buy a new tv and your mom gave you:",
    "You lost 300$ but you were lucky and found:",
    "Martine the bot was so friendly and gave you:",
    "A friend you have never seen, sent some coins to your paypal:",
    "Look how lucky you are today:",
    "It's monday so your friend gave you some coins to buy food for today:",
    "You didn't find your coins so one of your family member gave you:",
    "You've worked for a week and got:",
    "Someone wanted to show how much they care about you so you got:",
]

# I need more words... honestly.
