name: "Bug report"
description: Create a report to help us improve
title: "[BUG]: "
labels: ["Status Pending"]
assignees:
  - ltzmax
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Before you report, make sure that the cog is up to date.
  - type: dropdown
    id: Cog
    attributes:
      label: Cog
      description: What cog are you getting issue from?
      options:
        - autopublisher
        - away
        - nospoiler
        - nekosbest
        - tcgcard
        - RolePlayCog
        - whosthatpokemon
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "What is the version of the cog?"
      placeholder: e.g 0.4.5 (You find versions in [p]help <CogName>.)
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Discord username
      description: Can you tell me your discord username so i can get in touch with you if i need more info?
      placeholder: e.g discord#1234 (This is Optional)
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell me, what did you expect to happen and what actually happened?
      placeholder: Tell me what happened and what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant error from your log. This will be automatically formatted into code, so no need for backticks.
      render: py
    validations:
      required: true
