name: "Feature request"
description: A feature request for a cog
title: "[Feature Request]: "
labels: ["Status Pending"]
assignees:
  - ltzmax
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make a feature request!
  - type: dropdown
    id: Cog
    attributes:
      label: Cog
      description: What cog are you feature requesting to?
      options:
        - autopublisher
        - away
        - nospoiler
        - nekosbest
        - tcgcard
        - RolePlayCog
        - whosthatpokemon
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Discord username
      description: Can you tell me your discord username so i can get in touch with you if i need more info?
      placeholder: ex. discord#1234 (This is Optional)
    validations:
      required: false
  - type: textarea
    id: what-you-want
    attributes:
      label: What feature do you want?
      description: Tell me, what do you want to see.
      placeholder: I want to see a new feature but what exactly is the feature and what does it do?
    validations:
      required: true
