name: auto_format

on: [push, pull_request]


jobs:
  black:
    name: Style Reformatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install black isort autoflake"
        name: Install requirements
      - run: "make reformat"
        continue-on-error: true
        name: Style reformatting
      - name: Commit changes
        continue-on-error: true
        run: |
          git config --local committer.email "noreply@github.com"
          git config --local committer.name "GitHub"
          git config --local author.email "${{ github.actor }}@users.noreply.github.com"
          git config --local author.name "{{ github.actor }}"
          git add -A
          git commit -m "Style Reformatting"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF#refs/heads/}
          
  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: "python -m pip install git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle git+https://github.com/pycqa/flake8@3.7.9#egg=flake8"
        name: Install Flake8
      - run: "python -m flake8 . --count --select=E9,F7,F82 --show-source"
        name: Flake8 Linting
