name: Lint Python
on:
  pull_request:
  push:
  repository_dispatch:
    types:
      - dispatched_test

env:
  ref: ${{ github.event.client_payload.ref || '' }}

jobs:
  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.ref }}
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.15.9"
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.15.9"
          args: "format --check"
