name: Checks

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    name: Style
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install black isort
      - name: Run black
        run: |
          python -m black --check --line-length 99 .
      - name: Run isort
        run: |
          python -m isort --check --line-length 99 --trailing-comma .
# Thanks vexed. :aha:
